// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.0
// source: pb/lenven.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Booking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	RoomID     string `protobuf:"bytes,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	UserID     string `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	NumPersons int64  `protobuf:"varint,4,opt,name=numPersons,proto3" json:"numPersons,omitempty"`
	FromDate   string `protobuf:"bytes,5,opt,name=fromDate,proto3" json:"fromDate,omitempty"`
	TillDate   string `protobuf:"bytes,6,opt,name=tillDate,proto3" json:"tillDate,omitempty"`
	Canceled   bool   `protobuf:"varint,7,opt,name=canceled,proto3" json:"canceled,omitempty"`
}

func (x *Booking) Reset() {
	*x = Booking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lenven_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lenven_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_pb_lenven_proto_rawDescGZIP(), []int{0}
}

func (x *Booking) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Booking) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *Booking) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Booking) GetNumPersons() int64 {
	if x != nil {
		return x.NumPersons
	}
	return 0
}

func (x *Booking) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *Booking) GetTillDate() string {
	if x != nil {
		return x.TillDate
	}
	return ""
}

func (x *Booking) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

type CreateBookingParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromDate   string `protobuf:"bytes,1,opt,name=fromDate,proto3" json:"fromDate,omitempty"`
	TillDate   string `protobuf:"bytes,2,opt,name=tillDate,proto3" json:"tillDate,omitempty"`
	NumPersons int64  `protobuf:"varint,3,opt,name=numPersons,proto3" json:"numPersons,omitempty"`
}

func (x *CreateBookingParams) Reset() {
	*x = CreateBookingParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lenven_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingParams) ProtoMessage() {}

func (x *CreateBookingParams) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lenven_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingParams.ProtoReflect.Descriptor instead.
func (*CreateBookingParams) Descriptor() ([]byte, []int) {
	return file_pb_lenven_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookingParams) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *CreateBookingParams) GetTillDate() string {
	if x != nil {
		return x.TillDate
	}
	return ""
}

func (x *CreateBookingParams) GetNumPersons() int64 {
	if x != nil {
		return x.NumPersons
	}
	return 0
}

type CreateBookingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingResult *Booking `protobuf:"bytes,1,opt,name=bookingResult,proto3" json:"bookingResult,omitempty"`
}

func (x *CreateBookingResp) Reset() {
	*x = CreateBookingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lenven_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResp) ProtoMessage() {}

func (x *CreateBookingResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lenven_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResp.ProtoReflect.Descriptor instead.
func (*CreateBookingResp) Descriptor() ([]byte, []int) {
	return file_pb_lenven_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookingResp) GetBookingResult() *Booking {
	if x != nil {
		return x.BookingResult
	}
	return nil
}

type GetBookingsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBookingsReq) Reset() {
	*x = GetBookingsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lenven_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingsReq) ProtoMessage() {}

func (x *GetBookingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lenven_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingsReq.ProtoReflect.Descriptor instead.
func (*GetBookingsReq) Descriptor() ([]byte, []int) {
	return file_pb_lenven_proto_rawDescGZIP(), []int{3}
}

type GetBookingsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookings []*Booking `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
}

func (x *GetBookingsResp) Reset() {
	*x = GetBookingsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lenven_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingsResp) ProtoMessage() {}

func (x *GetBookingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lenven_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingsResp.ProtoReflect.Descriptor instead.
func (*GetBookingsResp) Descriptor() ([]byte, []int) {
	return file_pb_lenven_proto_rawDescGZIP(), []int{4}
}

func (x *GetBookingsResp) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type GetBookingByIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetBookingByIDReq) Reset() {
	*x = GetBookingByIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lenven_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookingByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingByIDReq) ProtoMessage() {}

func (x *GetBookingByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lenven_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingByIDReq.ProtoReflect.Descriptor instead.
func (*GetBookingByIDReq) Descriptor() ([]byte, []int) {
	return file_pb_lenven_proto_rawDescGZIP(), []int{5}
}

func (x *GetBookingByIDReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetBookingByIDResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingResult *Booking `protobuf:"bytes,1,opt,name=bookingResult,proto3" json:"bookingResult,omitempty"`
}

func (x *GetBookingByIDResp) Reset() {
	*x = GetBookingByIDResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lenven_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookingByIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingByIDResp) ProtoMessage() {}

func (x *GetBookingByIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lenven_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingByIDResp.ProtoReflect.Descriptor instead.
func (*GetBookingByIDResp) Descriptor() ([]byte, []int) {
	return file_pb_lenven_proto_rawDescGZIP(), []int{6}
}

func (x *GetBookingByIDResp) GetBookingResult() *Booking {
	if x != nil {
		return x.BookingResult
	}
	return nil
}

type CancelBookingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *CancelBookingReq) Reset() {
	*x = CancelBookingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lenven_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelBookingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingReq) ProtoMessage() {}

func (x *CancelBookingReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lenven_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingReq.ProtoReflect.Descriptor instead.
func (*CancelBookingReq) Descriptor() ([]byte, []int) {
	return file_pb_lenven_proto_rawDescGZIP(), []int{7}
}

func (x *CancelBookingReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type CancelBookingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CancelBookingResp) Reset() {
	*x = CancelBookingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_lenven_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelBookingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResp) ProtoMessage() {}

func (x *CancelBookingResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_lenven_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResp.ProtoReflect.Descriptor instead.
func (*CancelBookingResp) Descriptor() ([]byte, []int) {
	return file_pb_lenven_proto_rawDescGZIP(), []int{8}
}

func (x *CancelBookingResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_lenven_proto protoreflect.FileDescriptor

var file_pb_lenven_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x6c, 0x65, 0x6e, 0x76, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xbd, 0x01, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x74, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x74, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x65, 0x64, 0x22, 0x6d, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6c, 0x6c,
	0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6c, 0x6c,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x73, 0x22, 0x46, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0d, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x0d, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x10, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x22, 0x3a,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x27, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x47, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0d, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x0d, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x22, 0x0a, 0x10, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x25, 0x0a, 0x11,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x32, 0x88, 0x02, 0x0a, 0x06, 0x4c, 0x65, 0x6e, 0x76, 0x65, 0x6e, 0x12, 0x41,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12,
	0x17, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x38, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73,
	0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x49, 0x44, 0x12, 0x15, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3e,
	0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12,
	0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x07,
	0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_lenven_proto_rawDescOnce sync.Once
	file_pb_lenven_proto_rawDescData = file_pb_lenven_proto_rawDesc
)

func file_pb_lenven_proto_rawDescGZIP() []byte {
	file_pb_lenven_proto_rawDescOnce.Do(func() {
		file_pb_lenven_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_lenven_proto_rawDescData)
	})
	return file_pb_lenven_proto_rawDescData
}

var file_pb_lenven_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_lenven_proto_goTypes = []interface{}{
	(*Booking)(nil),             // 0: pb.Booking
	(*CreateBookingParams)(nil), // 1: pb.CreateBookingParams
	(*CreateBookingResp)(nil),   // 2: pb.CreateBookingResp
	(*GetBookingsReq)(nil),      // 3: pb.GetBookingsReq
	(*GetBookingsResp)(nil),     // 4: pb.GetBookingsResp
	(*GetBookingByIDReq)(nil),   // 5: pb.GetBookingByIDReq
	(*GetBookingByIDResp)(nil),  // 6: pb.GetBookingByIDResp
	(*CancelBookingReq)(nil),    // 7: pb.CancelBookingReq
	(*CancelBookingResp)(nil),   // 8: pb.CancelBookingResp
}
var file_pb_lenven_proto_depIdxs = []int32{
	0, // 0: pb.CreateBookingResp.bookingResult:type_name -> pb.Booking
	0, // 1: pb.GetBookingsResp.bookings:type_name -> pb.Booking
	0, // 2: pb.GetBookingByIDResp.bookingResult:type_name -> pb.Booking
	1, // 3: pb.Lenven.CreateBooking:input_type -> pb.CreateBookingParams
	3, // 4: pb.Lenven.GetBookings:input_type -> pb.GetBookingsReq
	5, // 5: pb.Lenven.GetBookingByID:input_type -> pb.GetBookingByIDReq
	7, // 6: pb.Lenven.CancelBooking:input_type -> pb.CancelBookingReq
	2, // 7: pb.Lenven.CreateBooking:output_type -> pb.CreateBookingResp
	4, // 8: pb.Lenven.GetBookings:output_type -> pb.GetBookingsResp
	6, // 9: pb.Lenven.GetBookingByID:output_type -> pb.GetBookingByIDResp
	8, // 10: pb.Lenven.CancelBooking:output_type -> pb.CancelBookingResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_lenven_proto_init() }
func file_pb_lenven_proto_init() {
	if File_pb_lenven_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_lenven_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Booking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lenven_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBookingParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lenven_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBookingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lenven_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookingsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lenven_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookingsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lenven_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookingByIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lenven_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookingByIDResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lenven_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelBookingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_lenven_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelBookingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_lenven_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_lenven_proto_goTypes,
		DependencyIndexes: file_pb_lenven_proto_depIdxs,
		MessageInfos:      file_pb_lenven_proto_msgTypes,
	}.Build()
	File_pb_lenven_proto = out.File
	file_pb_lenven_proto_rawDesc = nil
	file_pb_lenven_proto_goTypes = nil
	file_pb_lenven_proto_depIdxs = nil
}
